### ISSUE TITLE
Используй стандратные типы (C99+)

### ISSUE THREAD

**Issue by vp1981** [Meowushky/Magnus-expansion#2]
https://github.com/Meowushky/Magnus-expansion/blob/956d1396fcef9febdf1063909b55c8e08e5e430b/M4/M4.c#L107

При подключении заголовочного файла `stdbool.h` вводится тип `bool`, используй его, а не нестандартный `_Bool` (тип `bool` стал стандартным начиная с C99 и далее, мы работаем с C11, к тому же тип `bool` есть в C++, а вот `_Bool` — отсутствует!).

**Comment by Meowushky** [comment]
Сначала я писала `bool`, но он не подсвечивался, и я подумала, что такого нет. А вот `_Bool` подсвечивался.
Переделала на  `bool`, в общем, работает, спасибо.
